name: Python CI  ## Just the name of the workflow

## Define events that trigger the workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  ## This is a Ubuntu latest container; we can also use Windows and Mac containers

    steps:

        ##checkout the code from the repo
      - name: Check out code
        uses: actions/checkout@v2  ##provided my github actions


        ##setup the python environment
      - name: Set up Python
        uses: actions/setup-python@v2 ##provided my github actions
        with:
          python-version: '3.8'
          

          ##install all the dependencies
      - name: Install dependencies 
      ##here we have to run 2 commands for that 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

        ## run tests
      - name: Run tests
        run: pytest  
